apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  ports:
    - name: server
      port: 8848
      protocol: TCP
      targetPort: 8848
    - name: rpc
      port: 7848
      protocol: TCP
      targetPort: 7848
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}