version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    hostname: nacos
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == master
    networks:
      - structure-cloud-work
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - ./logs:/home/nacos/logs
      - ./data:/home/nacos/data
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
      - 7848:7848
    restart: always
networks:
  structure-cloud-work:
    driver: overlay
    external: true