{{- if .Values.gateway.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iam.fullname" . }}-gateway
  labels:
    {{- include "iam.labels" . | nindent 4 }}
    app.service: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "iam.selectorLabels" . | nindent 6 }}
      app.service: gateway
  template:
    metadata:
      labels:
        {{- include "iam.selectorLabels" . | nindent 8 }}
        app.service: gateway
    spec:
      serviceAccountName: {{ include "iam.serviceAccountName" . }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iam.fullname" . }}-gateway
  labels:
    {{- include "iam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iam.selectorLabels" . | nindent 4 }}
    app.service: gateway
{{- end }}
