version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    restart: always  #每次总是启动
    hostname: postgres
    networks:
      - structure-cloud-work
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == master
    ports:
      - "5432:5432"
networks:
  structure-cloud-work:
    driver: overlay
    external: true