{{- range $key, $svc := dict "backend" .Values.backend "frontend" .Values.frontend }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "structure-risk-center.fullname" $ }}-{{ $svc.name }}
  labels:
    {{- include "structure-risk-center.labels" $ | nindent 4 }}
    app.service: {{ $svc.name }}
spec:
  type: {{ $svc.service.type }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "structure-risk-center.selectorLabels" $ | nindent 4 }}
    app.service: {{ $svc.name }}
{{- end }}
{{- end }}
