{{- if .Values.ingress.enabled }}
{{- range $key, $svc := dict "frontend1" .Values.frontend1 "frontend2" .Values.frontend2 "frontend3" .Values.frontend3 "frontend4" .Values.frontend4 }}
{{- if $svc.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "structure-portal-center.fullname" $ }}-{{ $svc.name }}
  labels:
    {{- include "structure-portal-center.labels" $ | nindent 4 }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range $.Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "structure-portal-center.fullname" $ }}-{{ $svc.name }}
                port:
                  number: {{ $svc.service.port }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
