version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis-single
    restart: always
    networks:
      - structure-cloud-work
    ports:
      - "6379:6379"
    volumes:
      - ./conf:/etc/redis/conf:rw
      - ./data:/data:rw
    command:
      # 执行的命令
      redis-server /etc/redis/conf/redis.conf --appendonly yes
networks:
  structure-cloud-work:
    driver: overlay
    external: true