kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "web-pc-manager-ui.fullname" . }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    
    
    events {
      worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';
      
      access_log  /var/log/nginx/access.log  main;
      
      sendfile        on;
      #tcp_nopush     on;
      
      keepalive_timeout  65;
      
      #gzip  on;
      
      #include /etc/nginx/conf.d/*.conf;
      server{
        listen      80;
        server_name localhost;
        location / {
          root  /usr/share/nginx/html/;
          index index.html;
        }
        location /api {
          rewrite ^/api/(.*) /$1 break;
          proxy_pass http://admin-api.yueyankeji.com;
          proxy_set_header Host $proxy_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-ORGANIZATION_ID 100;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
