---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-headless
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: amqp
      port: 5672
    - name: http
      port: 15672
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}