version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    restart: always
    networks:
      - structure-cloud-work
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:rw
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
      - 15692:15692
      - 25672:25672
    environment:
      RABBITMQ_DEFAULT_VHOST: '/'
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
networks:
  structure-cloud-work:
    driver: overlay
    external: true