version: '3.8'
services:
  #mysql容器
  mysql:
    #是否跟随docker启动
    restart: always
    hostname: mysql
    #容器名称
    container_name: mysql
    #镜像
    image: mysql:8.0.25
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == master
    networks:
      - structure-cloud-work
    #映射端口
    ports:
      - "3306:3306"
    #挂载目录
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql/
      - ./init.d:/docker-entrypoint-initdb.d/:ro
      - ./config:/etc/mysql/conf.d/:rw
    #环境变量
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
    - "--server-id=1"
    - "--default-authentication-plugin=mysql_native_password"
    - "--character-set-server=utf8mb4"
    - "--max_connections=16384"
    - "--collation-server=utf8mb4_general_ci"
    - "--explicit_defaults_for_timestamp=true"
    - "--lower_case_table_names=1"
    - "--binlog-ignore-db=mysql"
    - "--binlog_format=row"
    - "--log-bin=mysql-bin"
    - "--sync_binlog=1"
    - "--expire_logs_days=7"
    - "--slave_skip_errors=1062"
    - "--sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
networks:
  structure-cloud-work:
    driver: overlay
    external: true