apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "manager-system.fullname" . }}
  labels:
    {{- include "manager-system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "manager-system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "manager-system.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "manager-system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.configmap.enabled -}}
          volumeMounts:
            - mountPath: /app/config/
              name: app-config
          {{- end }}
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - /app/liveness.sh
            initialDelaySeconds: 50
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - /app/liveness.sh
          env:
            - name: PARAMS
              value: {{ .Values.env.params }}
            - name: JAVA_OPTS
              value: {{ .Values.env.java_opts }}
            - name: APP_PATH
              value: {{ .Values.env.app_path }}
            { { - end } }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configmap.enabled -}}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "manager-system.fullname" . }}
      {{- end }}